//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDKrishokDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Diseases = new HashSet<Disease>();
            this.Medicine1 = new HashSet<Medicine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Power { get; set; }
        public string SideEffect { get; set; }
        public Nullable<int> MedicineTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public string Description { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disease> Diseases { get; set; }
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine> Medicine1 { get; set; }
        public virtual Medicine Medicine2 { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual Video Video { get; set; }
    }
}
